name: cleanarch_dart
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/RafaelSilvaPereira/cleanarch_dart

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  path: ^1.8.0
  recase: ^4.0.0
